'use client'

import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import useModalStore from '@/lib/store/useModal'
import Menu from './components/Menu';

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Complete Doctor",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { isMenuOpen } = useModalStore()
  
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased relative`}
      >
        <Navbar />
        {isMenuOpen && <Menu />}
        {children}
      </body>
    </html>
  );
}
